import argparse
import pickle
from pathlib import Path
from markov_chain import MarkovChain

def generate_sequence(model, length=100, start_token=None):
    return model.generate(length=length, start_token=start_token)

def main():
    parser = argparse.ArgumentParser(description="Generate synthetic SMT files using a trained MarkovChain model.")
    parser.add_argument('--model', type=str, required=True, help='Path to the trained MarkovChain model (pickle file)')
    parser.add_argument('--output_dir', type=str, required=True, help='Directory to save the generated SMT files')
    parser.add_argument('--num_files', type=int, default=1, help='Number of SMT files to generate')
    parser.add_argument('--length', type=int, default=150, help='Approximate length of the sequence to generate')
    parser.add_argument('--start', type=str, default=None, help='Optional start token for generation')
    args = parser.parse_args()

    # Load the trained MarkovChain model
    with open(args.model, 'rb') as f:
        model = pickle.load(f)
    if not isinstance(model, MarkovChain):
        raise ValueError('Loaded object is not a MarkovChain instance')

    # Create output directory if it doesn't exist
    output_path = Path(args.output_dir)
    output_path.mkdir(parents=True, exist_ok=True)

    print(f"Generating {args.num_files} synthetic SMT files in {args.output_dir}...")

    for i in range(args.num_files):
        # Generate sequence
        sequence = generate_sequence(model, length=args.length, start_token=args.start)
        
        # Define output file path
        output_file = output_path / f"synthetic_score_{i+1}.smt"

        # Prepare metadata
        metadata = [
            f"title[Synthetic Score {i+1}]",
            f"subtitle[Generated by RhythmForm Markov Model]",
            "creator[RhythmForm]",
            "clef[percussion]"
        ]
        
        # Combine metadata with the generated sequence
        full_sequence = metadata + sequence

        # Write sequence to file
        with open(output_file, 'w') as out_f:
            out_f.write(" ".join(full_sequence))
    
    print(f"Successfully generated {args.num_files} files.")

if __name__ == "__main__":
    main()
